### ISSUE TITLE
`OpenbyDesign` TOC and tracking migration from `psych-open-science` to `OpenByDesign`

### ISSUE THREAD

**Issue by franklin-feingold** [DSI-CORES/OpenByDesign#3]
UI rendering: https://dsi-cores.github.io/OpenByDesign/README.html

This ticket intends to convey our handbook organization and track our progress for converting [psych-open-science](https://github.com/poldrack/psych-open-science-guide) documents into our domain-general content. The file organization is a proposed initialization - we can move around and link together the modular pieces after the migration is complete. 

We can store the source document under a `src` folder. Our naming scheme can follow `01-introduction.md`. If a section has multiple files, these files can be stored in a folder following the same naming scheme. For example `02-sample` is the folder with `01-subsample.md` and `02-subexample.md` within. 

This schema makes our organization more modular and easy to fit into our rendering solution - [Jupyter Book](https://jupyterbook.org/intro.html). We can store the generated html files on the `gh-pages` branch. Within the file, I have listed a proposed initial set of sections denoted by `:`. We can initialize a `CODEOWNERS` file for community members to maintain their files of interest.

The handbook organizational scheme will be: Chapter -> Section -> Topic

edit 4/6: incorporated a redesign of Chapters 1, 2, and 3

_Chapter 0: Introduction to the `Open By Design` handbook_ - addressed in https://github.com/DSI-CORES/OpenByDesign/pull/15

- [x] What is "open science"?
- [x] The components of open science practice
- [x] Why should I do it?
- [x] How this book is organized
- [x] Contributors
- [x] License

Learning more about the Open Science community/ - addressed in https://github.com/DSI-CORES/OpenByDesign/pull/16
- [x] Open Science resources: Blogs, Books, Courses, People/Twitter handles, podcasts, foundational papers, talks
- [x] Doing Open Science: Tools/Platforms, Initiatives/Collaborations, Organizations/Centers/Labs, Societies/Conferences, Hackathons, Journals, Funding & Grants

_Chapter 1: Research practices (practical)_

- [x] Pre-registration: What is pre-registration, Why is pre-registration important?, Embedding pre-registration into the research process, Getting started, Learn more, FAQ - (partially addressed in https://github.com/DSI-CORES/OpenByDesign/pull/9)
- [x] Reproducible data analysis: Committing to reproducibility, Embedding reproducible data analysis into the research process, Prerequisities, Getting started, Advanced steps, Learn more, FAQ - (partially addressed in https://github.com/DSI-CORES/OpenByDesign/pull/7)
- [ ] Reproducible modeling: What is reproducible modeling, Why should I share my model?, Embedding reproducible modeling into the research process, Getting started, Learn more, FAQ
- [x] Reproducible manuscript: What is a reproducible manuscript, Embedding a reproducible manuscript into the research process, Prerequisites, Getting started, Advanced topic: Containerizing and automating your reproducible manuscript, Learn more, FAQ - (partially addressed in https://github.com/DSI-CORES/OpenByDesign/pull/10)
- [ ] Reproducible project: What is a reproducible project, Why is a reproducible project important?, Embedding a reproducible project into the research process, Getting started, Learn more, FAQ

Sharing research objects beyond the text/
- [x] Code sharing: What is code sharing, Why should I share my code?, Embedding code sharing into the research process, Prerequisites, Getting started, When you are ready to publish your work, Learn more, FAQ - (partially addressed in https://github.com/DSI-CORES/OpenByDesign/pull/11)
- [X] Data sharing: What is data sharing, Why should I share my data?, Why doesn't everyone share their data?, What are "metadata" and why are they important?, The FAIR principles for open data, Embedding data sharing into the research process, Getting started, Learn more, FAQ - (partially addressed in https://github.com/DSI-CORES/OpenByDesign/pull/12)

_Chapter 2: Open Science infrastructure_

[Edit 9/20]: Proposing a layer of organization above these sections: Computer Literacy, Programming, and Project Management. This additional layer will enhance our management of this section and focus on further extensions and development.

Computer Literacy/
- [x] Computer literacy: File systems, Files, Command line, Editing text files; (within each topic) What is it, Why is it important, FAQ, Common use cases, Learn more - (partially addressed in https://github.com/DSI-CORES/OpenByDesign/pull/13)
- [ ] Data structures: What are data structures, Why are they important?, FAQ, Common use cases, Learn more  
- [ ] Metadata: What is metadata, Why is metadata important?, FAQ, Common use cases, Learn more 

Programming/
- [ ] Computing languages: Python, R; (for each language) What is the computing language, Why are these important?, FAQ, Common use cases, Learn more
- [x] UNIX: Makefiles; What are Makefiles, Why are they important?, FAQ, Common use cases, Learn more - (partially addressed in https://github.com/DSI-CORES/OpenByDesign/pull/14)
- [ ] Git: What is git, Why is it important?, FAQ, Common use cases, Learn more

Project Management/
- [ ] Version Control: What is version control, Why is it important?, FAQ, Common use cases, Learn more
- [ ] Collaborating with GitHub: Introduction (what is GitHub and why is it important), Repository initialization, Project communication, Working with contributors, Tips and FAQ, Common use cases, Learn more
- [ ] Reproducible environments: Package manager, Interactive notebooks, Containerization; (within each solution) What is it, Why is it important?, FAQ, Common use cases, Learn more
- [ ] Code testing: What is code testing, Why is it important?, Types of tests, FAQ, Common use cases, Learn more
- [ ] Code reviewing: What is code reviewing, Why is it important?, Guidelines, Checklist, FAQ, Common use cases, Learn more
- [ ] Continuous integration: What is continuous integration, Why is it important?, FAQ, Common use cases, Learn more
- [ ] High-Performance Computing resources: What is high-performance computing, Why is it important?, FAQ, Common use cases, Learn more

_Chapter 3: Examples_

Collection of Open Science examples. Include the previous [psych examples](https://github.com/poldrack/psych-open-science-guide/blob/master/guide/examples.md)

Open Science practices in research/
[Organized by domain]

[Open Science software and toolboxes/
[Organized by domain]

**Comment by MarioMalicki** [comment]
My suggestion would be to restructure the book in the following way: 

Chapter 0: Introduction
Chapter 1: Open study planning and registration

1. Specify your research question
2. Conduct a good literature search / reduce research waste
3. Form a team - Agree on authorship
4. Develop study design and analysis
5. Develop your data management plan
6. Preregister your study

Chapter 2:  Open study conduct and reporting

1. Code Sharing
2. Data Sharing
3. Open data collection
4. Live systematic review
5. Open lab notes/workflows
6. Open manuscript writing
7. Reproducible data analysis
8. Reproducible modeling
9. Reproducible manuscript
10. Reproducible project
11. Open access publication

Chapter 3: Other aspect of open science

1. Open reviews
2. Open teaching materials
3. open infrastructure
4. open policies
5. open tools

alternatively we can mention in intro we will not be covering this in detail

**Comment by franklin-feingold** [comment]
posting here - perhaps may you please share what the subsections may look like? describing similar to how I did above?

**Comment by MarioMalicki** [comment]
I didn't want to add subsections initially, as I am not sure there is agreement on the current chapters -e.g. what subsections  all chapters should have. I really love your idea - and would expect all to start with: What is X? Why do X? Guide to doing X. Case examples. FAQ. Additional resources.

**Comment by franklin-feingold** [comment]
that sounds good! adding a reminder note: update the TOC to reflect this consistent organization
